# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=DP-1,5140x1440@240,0x0,1,bitdepth,10,cm,hdr,sdrbrightness,1.3,sdrsaturation,1
monitor=HDMI-A-1,3440x1440@85,0x0,1,bitdepth,10

gestures {
  workspace_swipe_invert = true
}

general {
  layout = dwindle
  # gaps_in = 4
  # gaps_out = 8
  # border_size = 1
}

dwindle {
  pseudotile = true
}

master {
  orientation = center
  new_status = slave
  slave_count_for_center_master = 0
  always_keep_position = true
  mfact = 0.65
}

decoration {
  # rounding = 12
  active_opacity = 1.0
  inactive_opacity = 0.90
}

input {
  kb_layout = us,ru
  kb_options = caps:ctrl_modifier
  repeat_rate = 50
  repeat_delay = 300
  sensitivity = 0
  accel_profile = flat
  scroll_method = 2fg
  natural_scroll = false
  follow_mouse = 2

  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
    scroll_factor = 0.3
    tap-to-click = true
  }
}

animations {
  enabled = yes
  animation = windows, 0
  animation = windowsMove, 1, 4, default
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = fadeIn, 0
  animation = fadeOut, 0
  animation = workspaces, 1, 4, default, fade
  animation = specialWorkspaceIn, 1, 4, default, fade
  animation = specialWorkspaceOut, 1, 4, default, fade
}

misc {
  # Fix brightness flickeing
  vrr = 2
  # Fix telegram and other apps from stealing focus on notifications
  focus_on_activate = true
}

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
