# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*
# windowrule = match:class kitty, no_blur off

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
windowrule = match:fullscreen true, decorate off
windowrule = match:initial_class obsidian, pseudo on, size 3440 1440
windowrule = match:initial_title Media viewer, float on
windowrule = match:class pavucontrol-qt, float on
windowrule = match:class org.kde.dolphin, float on, size 1800 1260
windowrule = match:class spotify, float on, size 1800 1260

windowrule = match:class zen, pseudo on, size 3458 1440
windowrule = match:class kitty, size 3440 1440
windowrule = match:title btop, float on
# windowrule = match:class .*, suppress_event maximize
# windowrule = match:class .*, suppress_event float
windowrule = match:class .*, suppress_event fullscreen 2

layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

# disable animation for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:DP-1
workspace = 11, monitor:DP-1
workspace = 12, monitor:DP-1
workspace = 13, monitor:DP-1
workspace = 14, monitor:DP-1
workspace = 15, monitor:DP-1
workspace = 16, monitor:DP-1
workspace = 17, monitor:DP-1
workspace = 18, monitor:DP-1
workspace = 19, monitor:DP-1
workspace = 20, monitor:DP-1
workspace = 10, monitor:HDMI-A-1
workspace = 11, monitor:HDMI-A-1
workspace = 12, monitor:HDMI-A-1
workspace = 13, monitor:HDMI-A-1
workspace = 14, monitor:HDMI-A-1
workspace = 15, monitor:HDMI-A-1
workspace = 16, monitor:HDMI-A-1
workspace = 17, monitor:HDMI-A-1
workspace = 18, monitor:HDMI-A-1
workspace = 19, monitor:HDMI-A-1
workspace = 20, monitor:HDMI-A-1
